services:
  db:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      # Senha do usuário root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # Cria um banco de dados automaticamente na inicialização
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # Cria um usuário comum (melhor prática que usar root)
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  backend-network:
    driver: bridge